FROM python:3.11-slim
WORKDIR /app
RUN groupadd -r appuser && useradd -r -g appuser appuser
RUN mkdir -p /data && chown -R appuser:appuser /data
RUN mkdir -p /app/logs && chown -R appuser:appuser /app/logs
RUN mkdir -p /app/static && chown -R appuser:appuser /app/static
RUN apt-get update && apt-get install -y curl  # Добавляем curl
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY main.py .
COPY utils/ ./utils
COPY models/ ./models
RUN chown -R appuser:appuser /app
USER appuser
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]