services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
      target: ${BUILD_TARGET:-development}
    environment:
      # Основные настройки
      - DEBUG=${DEBUG:-true}
      - HOST=${HOST:-0.0.0.0}
      - PORT=${PORT:-8000}
      - ENVIRONMENT=development

      # Telegram Bot
      - BOT_TOKEN=${BOT_TOKEN}
      - ADMIN_TELEGRAM_ID=${ADMIN_TELEGRAM_ID}
      - BOT_LINK=${BOT_LINK}
      - INVITE_LINK=${INVITE_LINK}
      - GROUP_ID=${GROUP_ID}
      - FOR_LOGS=${FOR_LOGS}

      # Безопасность
      - SECRET_KEY=${SECRET_KEY}
      - SECRET_KEY_JWT=${SECRET_KEY_JWT}
      - ADMIN_LOGIN=${ADMIN_LOGIN}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}

      # API - локальные настройки
      - API_BASE_URL=http://web:8000
      - FRONTEND_URL=http://localhost
      - CORS_ORIGINS=http://localhost,http://127.0.0.1

      # Backup настройки
      - BACKUP_ENABLED=${BACKUP_ENABLED:-false}
      - BACKUP_INTERVAL_HOURS=${BACKUP_INTERVAL_HOURS:-6}
      - BACKUP_DIR=/app/data/backups

      # Логирование
      - LOG_LEVEL=${LOG_LEVEL:-DEBUG}
      - LOG_FORMAT=${LOG_FORMAT:-text}
      - LOG_TO_FILE=${LOG_TO_FILE:-true}

      # Кэширование
      - REDIS_URL=redis://redis:6379/0

      # Внешние URL
      - ADMIN_URL=${ADMIN_URL:-https://t.me/partacoworking}
      - RULES_URL=${RULES_URL:-https://parta-works.ru/main_rules}
    volumes:
      - data_volume:/app/data
      - avatars_volume:/app/avatars
      - ticket_photos_volume:/app/ticket_photos
      - newsletter_photos_volume:/app/newsletter_photos
      - logs_volume:/app/logs
      - config_volume:/app/config
    restart: unless-stopped
    depends_on:
      web:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "test", "-f", "/app/data/bot_initialized"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - coworking_network

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
      target: ${BUILD_TARGET:-development}
    environment:
      # Основные настройки
      - DEBUG=${DEBUG:-true}
      - HOST=${HOST:-0.0.0.0}
      - PORT=${PORT:-8000}
      - ENVIRONMENT=development
      - APP_NAME=${APP_NAME:-Coworking API}
      - APP_VERSION=${APP_VERSION:-1.0.0}

      # Сетевые настройки - локальные
      - API_BASE_URL=http://localhost:8000/api
      - FRONTEND_URL=http://localhost
      - CORS_ORIGINS=http://localhost,http://127.0.0.1,http://localhost:3000,http://localhost:5173

      # Безопасность
      - SECRET_KEY=${SECRET_KEY}
      - SECRET_KEY_JWT=${SECRET_KEY_JWT}
      - ACCESS_TOKEN_EXPIRE_HOURS=${ACCESS_TOKEN_EXPIRE_HOURS:-24}
      - ADMIN_LOGIN=${ADMIN_LOGIN}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}

      # Telegram Bot
      - BOT_TOKEN=${BOT_TOKEN}
      - ADMIN_TELEGRAM_ID=${ADMIN_TELEGRAM_ID}
      - BOT_LINK=${BOT_LINK}
      - INVITE_LINK=${INVITE_LINK}
      - GROUP_ID=${GROUP_ID}
      - FOR_LOGS=${FOR_LOGS}

      # Платежные системы
      - YOKASSA_ACCOUNT_ID=${YOKASSA_ACCOUNT_ID}
      - YOKASSA_SECRET_KEY=${YOKASSA_SECRET_KEY}

      # Rubitime
      - RUBITIME_API_KEY=${RUBITIME_API_KEY}
      - RUBITIME_BASE_URL=${RUBITIME_BASE_URL:-https://rubitime.ru/api2/}
      - RUBITIME_BRANCH_ID=${RUBITIME_BRANCH_ID:-12595}
      - RUBITIME_COOPERATOR_ID=${RUBITIME_COOPERATOR_ID:-25786}

      # База данных
      - DB_TIMEOUT=${DB_TIMEOUT:-60}
      - DB_RETRY_ATTEMPTS=${DB_RETRY_ATTEMPTS:-3}
      - DB_RETRY_DELAY=${DB_RETRY_DELAY:-0.1}

      # Файлы и лимиты
      - FILE_RETENTION_DAYS=${FILE_RETENTION_DAYS:-30}
      - MAX_FILE_SIZE_MB=${MAX_FILE_SIZE_MB:-10}

      # Логирование
      - LOG_LEVEL=${LOG_LEVEL:-DEBUG}
      - LOG_FORMAT=${LOG_FORMAT:-text}
      - LOG_TO_FILE=${LOG_TO_FILE:-true}

      # Кэширование
      - REDIS_URL=redis://redis:6379/0
      - CACHE_DEFAULT_TTL=${CACHE_DEFAULT_TTL:-300}

      # Внешние URL
      - ADMIN_URL=${ADMIN_URL:-https://t.me/partacoworking}
      - RULES_URL=${RULES_URL:-https://parta-works.ru/main_rules}
    ports:
      - "${PORT:-8000}:8000"
    volumes:
      - data_volume:/app/data
      - avatars_volume:/app/avatars
      - ticket_photos_volume:/app/ticket_photos
      - newsletter_photos_volume:/app/newsletter_photos
      - logs_volume:/app/logs
      - config_volume:/app/config
    working_dir: /app
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - coworking_network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      target: development
      args:
        - REACT_APP_API_BASE_URL=http://localhost:8000/api
        - REACT_APP_FRONTEND_URL=http://localhost
    environment:
      - API_BASE_URL=http://localhost:8000/api
      - FRONTEND_URL=http://localhost
      - LOG_LEVEL=${LOG_LEVEL:-DEBUG}
    ports:
      - "${FRONTEND_PORT:-80}:80"
    restart: unless-stopped
    depends_on:
      web:
        condition: service_healthy
    networks:
      - coworking_network

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: >
      redis-server 
      --maxmemory ${REDIS_MAXMEMORY:-256mb}
      --maxmemory-policy allkeys-lru
      --save 60 1000
      --appendonly yes
      --appendfsync everysec
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s
    networks:
      - coworking_network

volumes:
  data_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/data
  avatars_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/avatars
  ticket_photos_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/ticket_photos
  newsletter_photos_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/newsletter_photos
  logs_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/logs
  config_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/config
  redis_data:
    driver: local

networks:
  coworking_network:
    driver: bridge